//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForsendelseClientSample.ForsendelsesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ks.no/svarut/services", ConfigurationName="ForsendelsesService.ForsendelsesServiceV4")]
    public interface ForsendelsesServiceV4 {
        
        // CODEGEN: Parameter 'forsendelsesid' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ForsendelseClientSample.ForsendelsesService.setForsendelseLestAvEksterntSystemResponse setForsendelseLestAvEksterntSystem(ForsendelseClientSample.ForsendelsesService.setForsendelseLestAvEksterntSystem request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ForsendelseClientSample.ForsendelsesService.retrieveForsendelseStatusResponse retrieveForsendelseStatus(ForsendelseClientSample.ForsendelsesService.retrieveForsendelseStatus request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractInstant))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ForsendelseClientSample.ForsendelsesService.retrieveForsendelseHistorikkResponse retrieveForsendelseHistorikk(ForsendelseClientSample.ForsendelsesService.retrieveForsendelseHistorikk request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractInstant))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ForsendelseClientSample.ForsendelsesService.sendForsendelseResponse sendForsendelse(ForsendelseClientSample.ForsendelsesService.sendForsendelse request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setForsendelseLestAvEksterntSystem", WrapperNamespace="http://www.ks.no/svarut/services", IsWrapped=true)]
    public partial class setForsendelseLestAvEksterntSystem {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ks.no/svarut/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string forsendelsesid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ks.no/svarut/services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lestAvFodselsnummer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ks.no/svarut/services", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string navnPaEksterntSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ks.no/svarut/services", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime datoLest;
        
        public setForsendelseLestAvEksterntSystem() {
        }
        
        public setForsendelseLestAvEksterntSystem(string forsendelsesid, string lestAvFodselsnummer, string navnPaEksterntSystem, System.DateTime datoLest) {
            this.forsendelsesid = forsendelsesid;
            this.lestAvFodselsnummer = lestAvFodselsnummer;
            this.navnPaEksterntSystem = navnPaEksterntSystem;
            this.datoLest = datoLest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setForsendelseLestAvEksterntSystemResponse", WrapperNamespace="http://www.ks.no/svarut/services", IsWrapped=true)]
    public partial class setForsendelseLestAvEksterntSystemResponse {
        
        public setForsendelseLestAvEksterntSystemResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public enum forsendelseStatus {
        
        /// <remarks/>
        MOTTATT,
        
        /// <remarks/>
        AKSEPTERT,
        
        /// <remarks/>
        AVVIST,
        
        /// <remarks/>
        VARSLET,
        
        /// <remarks/>
        LEST,
        
        /// <remarks/>
        SENDT_PRINT,
        
        /// <remarks/>
        PRINTET,
        
        /// <remarks/>
        MANUELT_HANDTERT,
        
        /// <remarks/>
        SENDT_DIGITALT,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveForsendelseStatus", WrapperNamespace="http://www.ks.no/svarut/services", IsWrapped=true)]
    public partial class retrieveForsendelseStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ks.no/svarut/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string forsendelsesid;
        
        public retrieveForsendelseStatus() {
        }
        
        public retrieveForsendelseStatus(string forsendelsesid) {
            this.forsendelsesid = forsendelsesid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveForsendelseStatusResponse", WrapperNamespace="http://www.ks.no/svarut/services", IsWrapped=true)]
    public partial class retrieveForsendelseStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ks.no/svarut/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ForsendelseClientSample.ForsendelsesService.forsendelseStatus @return;
        
        public retrieveForsendelseStatusResponse() {
        }
        
        public retrieveForsendelseStatusResponse(ForsendelseClientSample.ForsendelsesService.forsendelseStatus @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class hendelsesLogg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hendelseField;
        
        private string tidspunktField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hendelse {
            get {
                return this.hendelseField;
            }
            set {
                this.hendelseField = value;
                this.RaisePropertyChanged("hendelse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tidspunkt {
            get {
                return this.tidspunktField;
            }
            set {
                this.tidspunktField = value;
                this.RaisePropertyChanged("tidspunkt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class printkonfigurasjon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private brevtype brevtypeField;
        
        private bool brevtypeFieldSpecified;
        
        private bool fargePrintField;
        
        private bool tosidigField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public brevtype brevtype {
            get {
                return this.brevtypeField;
            }
            set {
                this.brevtypeField = value;
                this.RaisePropertyChanged("brevtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool brevtypeSpecified {
            get {
                return this.brevtypeFieldSpecified;
            }
            set {
                this.brevtypeFieldSpecified = value;
                this.RaisePropertyChanged("brevtypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool fargePrint {
            get {
                return this.fargePrintField;
            }
            set {
                this.fargePrintField = value;
                this.RaisePropertyChanged("fargePrint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool tosidig {
            get {
                return this.tosidigField;
            }
            set {
                this.tosidigField = value;
                this.RaisePropertyChanged("tosidig");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public enum brevtype {
        
        /// <remarks/>
        APOST,
        
        /// <remarks/>
        BPOST,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(organisasjon))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(privatPerson))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public abstract partial class mottaker : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string adresse1Field;
        
        private string adresse2Field;
        
        private string adresse3Field;
        
        private string landField;
        
        private string navnField;
        
        private string postnrField;
        
        private string poststedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adresse1 {
            get {
                return this.adresse1Field;
            }
            set {
                this.adresse1Field = value;
                this.RaisePropertyChanged("adresse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string adresse2 {
            get {
                return this.adresse2Field;
            }
            set {
                this.adresse2Field = value;
                this.RaisePropertyChanged("adresse2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string adresse3 {
            get {
                return this.adresse3Field;
            }
            set {
                this.adresse3Field = value;
                this.RaisePropertyChanged("adresse3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
                this.RaisePropertyChanged("land");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
                this.RaisePropertyChanged("navn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string postnr {
            get {
                return this.postnrField;
            }
            set {
                this.postnrField = value;
                this.RaisePropertyChanged("postnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
                this.RaisePropertyChanged("poststed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class organisasjon : mottaker {
        
        private string orgnrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orgnr {
            get {
                return this.orgnrField;
            }
            set {
                this.orgnrField = value;
                this.RaisePropertyChanged("orgnr");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class privatPerson : mottaker {
        
        private string fodselsnrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fodselsnr {
            get {
                return this.fodselsnrField;
            }
            set {
                this.fodselsnrField = value;
                this.RaisePropertyChanged("fodselsnr");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class entry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class noarkMetadataFraAvleverendeSakssystem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dateTime dokumentetsDatoField;
        
        private entry[] ekstraMetadataField;
        
        private int journalaarField;
        
        private dateTime journaldatoField;
        
        private int journalpostnummerField;
        
        private string journalposttypeField;
        
        private int journalsekvensnummerField;
        
        private string journalstatusField;
        
        private int saksaarField;
        
        private string saksbehandlerField;
        
        private int sakssekvensnummerField;
        
        private string tittelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dateTime dokumentetsDato {
            get {
                return this.dokumentetsDatoField;
            }
            set {
                this.dokumentetsDatoField = value;
                this.RaisePropertyChanged("dokumentetsDato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ekstraMetadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public entry[] ekstraMetadata {
            get {
                return this.ekstraMetadataField;
            }
            set {
                this.ekstraMetadataField = value;
                this.RaisePropertyChanged("ekstraMetadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int journalaar {
            get {
                return this.journalaarField;
            }
            set {
                this.journalaarField = value;
                this.RaisePropertyChanged("journalaar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public dateTime journaldato {
            get {
                return this.journaldatoField;
            }
            set {
                this.journaldatoField = value;
                this.RaisePropertyChanged("journaldato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int journalpostnummer {
            get {
                return this.journalpostnummerField;
            }
            set {
                this.journalpostnummerField = value;
                this.RaisePropertyChanged("journalpostnummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string journalposttype {
            get {
                return this.journalposttypeField;
            }
            set {
                this.journalposttypeField = value;
                this.RaisePropertyChanged("journalposttype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int journalsekvensnummer {
            get {
                return this.journalsekvensnummerField;
            }
            set {
                this.journalsekvensnummerField = value;
                this.RaisePropertyChanged("journalsekvensnummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string journalstatus {
            get {
                return this.journalstatusField;
            }
            set {
                this.journalstatusField = value;
                this.RaisePropertyChanged("journalstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
                this.RaisePropertyChanged("saksaar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string saksbehandler {
            get {
                return this.saksbehandlerField;
            }
            set {
                this.saksbehandlerField = value;
                this.RaisePropertyChanged("saksbehandler");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
                this.RaisePropertyChanged("sakssekvensnummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
                this.RaisePropertyChanged("tittel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class dateTime : baseDateTime {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dateTime))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public abstract partial class baseDateTime : abstractDateTime {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseDateTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dateTime))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public abstract partial class abstractDateTime : abstractInstant {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractDateTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseDateTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dateTime))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public abstract partial class abstractInstant : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class noarkMetadataForImport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dateTime dokumentetsDatoField;
        
        private string journalposttypeField;
        
        private string journalstatusField;
        
        private int saksaarField;
        
        private int sakssekvensnummerField;
        
        private string tittelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dateTime dokumentetsDato {
            get {
                return this.dokumentetsDatoField;
            }
            set {
                this.dokumentetsDatoField = value;
                this.RaisePropertyChanged("dokumentetsDato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string journalposttype {
            get {
                return this.journalposttypeField;
            }
            set {
                this.journalposttypeField = value;
                this.RaisePropertyChanged("journalposttype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string journalstatus {
            get {
                return this.journalstatusField;
            }
            set {
                this.journalstatusField = value;
                this.RaisePropertyChanged("journalstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
                this.RaisePropertyChanged("saksaar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
                this.RaisePropertyChanged("sakssekvensnummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
                this.RaisePropertyChanged("tittel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class lenke : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ledetekstField;
        
        private string urlLenkeField;
        
        private string urlTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ledetekst {
            get {
                return this.ledetekstField;
            }
            set {
                this.ledetekstField = value;
                this.RaisePropertyChanged("ledetekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string urlLenke {
            get {
                return this.urlLenkeField;
            }
            set {
                this.urlLenkeField = value;
                this.RaisePropertyChanged("urlLenke");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string urlTekst {
            get {
                return this.urlTekstField;
            }
            set {
                this.urlTekstField = value;
                this.RaisePropertyChanged("urlTekst");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class dokument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] dataField;
        
        private string filnavnField;
        
        private System.Nullable<int>[] giroarkSiderField;
        
        private string mimetypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string filnavn {
            get {
                return this.filnavnField;
            }
            set {
                this.filnavnField = value;
                this.RaisePropertyChanged("filnavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("giroarkSider", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int>[] giroarkSider {
            get {
                return this.giroarkSiderField;
            }
            set {
                this.giroarkSiderField = value;
                this.RaisePropertyChanged("giroarkSider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mimetype {
            get {
                return this.mimetypeField;
            }
            set {
                this.mimetypeField = value;
                this.RaisePropertyChanged("mimetype");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/svarut/services")]
    public partial class forsendelse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string avgivendeSystemField;
        
        private dokument[] dokumenterField;
        
        private string konteringskodeField;
        
        private bool krevNiva4InnloggingField;
        
        private bool kryptertField;
        
        private bool kunDigitalLeveringField;
        
        private lenke[] lenkerField;
        
        private noarkMetadataForImport metadataForImportField;
        
        private noarkMetadataFraAvleverendeSakssystem metadataFraAvleverendeSystemField;
        
        private mottaker mottakerField;
        
        private printkonfigurasjon printkonfigurasjonField;
        
        private string tittelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string avgivendeSystem {
            get {
                return this.avgivendeSystemField;
            }
            set {
                this.avgivendeSystemField = value;
                this.RaisePropertyChanged("avgivendeSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumenter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public dokument[] dokumenter {
            get {
                return this.dokumenterField;
            }
            set {
                this.dokumenterField = value;
                this.RaisePropertyChanged("dokumenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string konteringskode {
            get {
                return this.konteringskodeField;
            }
            set {
                this.konteringskodeField = value;
                this.RaisePropertyChanged("konteringskode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool krevNiva4Innlogging {
            get {
                return this.krevNiva4InnloggingField;
            }
            set {
                this.krevNiva4InnloggingField = value;
                this.RaisePropertyChanged("krevNiva4Innlogging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool kryptert {
            get {
                return this.kryptertField;
            }
            set {
                this.kryptertField = value;
                this.RaisePropertyChanged("kryptert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool kunDigitalLevering {
            get {
                return this.kunDigitalLeveringField;
            }
            set {
                this.kunDigitalLeveringField = value;
                this.RaisePropertyChanged("kunDigitalLevering");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lenker", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public lenke[] lenker {
            get {
                return this.lenkerField;
            }
            set {
                this.lenkerField = value;
                this.RaisePropertyChanged("lenker");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public noarkMetadataForImport metadataForImport {
            get {
                return this.metadataForImportField;
            }
            set {
                this.metadataForImportField = value;
                this.RaisePropertyChanged("metadataForImport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public noarkMetadataFraAvleverendeSakssystem metadataFraAvleverendeSystem {
            get {
                return this.metadataFraAvleverendeSystemField;
            }
            set {
                this.metadataFraAvleverendeSystemField = value;
                this.RaisePropertyChanged("metadataFraAvleverendeSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public mottaker mottaker {
            get {
                return this.mottakerField;
            }
            set {
                this.mottakerField = value;
                this.RaisePropertyChanged("mottaker");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public printkonfigurasjon printkonfigurasjon {
            get {
                return this.printkonfigurasjonField;
            }
            set {
                this.printkonfigurasjonField = value;
                this.RaisePropertyChanged("printkonfigurasjon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
                this.RaisePropertyChanged("tittel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveForsendelseHistorikk", WrapperNamespace="http://www.ks.no/svarut/services", IsWrapped=true)]
    public partial class retrieveForsendelseHistorikk {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ks.no/svarut/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string forsendelsesid;
        
        public retrieveForsendelseHistorikk() {
        }
        
        public retrieveForsendelseHistorikk(string forsendelsesid) {
            this.forsendelsesid = forsendelsesid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveForsendelseHistorikkResponse", WrapperNamespace="http://www.ks.no/svarut/services", IsWrapped=true)]
    public partial class retrieveForsendelseHistorikkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ks.no/svarut/services", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ForsendelseClientSample.ForsendelsesService.hendelsesLogg[] @return;
        
        public retrieveForsendelseHistorikkResponse() {
        }
        
        public retrieveForsendelseHistorikkResponse(ForsendelseClientSample.ForsendelsesService.hendelsesLogg[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendForsendelse", WrapperNamespace="http://www.ks.no/svarut/services", IsWrapped=true)]
    public partial class sendForsendelse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ks.no/svarut/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ForsendelseClientSample.ForsendelsesService.forsendelse forsendelse;
        
        public sendForsendelse() {
        }
        
        public sendForsendelse(ForsendelseClientSample.ForsendelsesService.forsendelse forsendelse) {
            this.forsendelse = forsendelse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendForsendelseResponse", WrapperNamespace="http://www.ks.no/svarut/services", IsWrapped=true)]
    public partial class sendForsendelseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ks.no/svarut/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendForsendelseResponse() {
        }
        
        public sendForsendelseResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ForsendelsesServiceV4Channel : ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForsendelsesServiceV4Client : System.ServiceModel.ClientBase<ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4>, ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4 {
        
        public ForsendelsesServiceV4Client() {
        }
        
        public ForsendelsesServiceV4Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForsendelsesServiceV4Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForsendelsesServiceV4Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForsendelsesServiceV4Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForsendelseClientSample.ForsendelsesService.setForsendelseLestAvEksterntSystemResponse ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4.setForsendelseLestAvEksterntSystem(ForsendelseClientSample.ForsendelsesService.setForsendelseLestAvEksterntSystem request) {
            return base.Channel.setForsendelseLestAvEksterntSystem(request);
        }
        
        public void setForsendelseLestAvEksterntSystem(string forsendelsesid, string lestAvFodselsnummer, string navnPaEksterntSystem, System.DateTime datoLest) {
            ForsendelseClientSample.ForsendelsesService.setForsendelseLestAvEksterntSystem inValue = new ForsendelseClientSample.ForsendelsesService.setForsendelseLestAvEksterntSystem();
            inValue.forsendelsesid = forsendelsesid;
            inValue.lestAvFodselsnummer = lestAvFodselsnummer;
            inValue.navnPaEksterntSystem = navnPaEksterntSystem;
            inValue.datoLest = datoLest;
            ForsendelseClientSample.ForsendelsesService.setForsendelseLestAvEksterntSystemResponse retVal = ((ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4)(this)).setForsendelseLestAvEksterntSystem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForsendelseClientSample.ForsendelsesService.retrieveForsendelseStatusResponse ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4.retrieveForsendelseStatus(ForsendelseClientSample.ForsendelsesService.retrieveForsendelseStatus request) {
            return base.Channel.retrieveForsendelseStatus(request);
        }
        
        public ForsendelseClientSample.ForsendelsesService.forsendelseStatus retrieveForsendelseStatus(string forsendelsesid) {
            ForsendelseClientSample.ForsendelsesService.retrieveForsendelseStatus inValue = new ForsendelseClientSample.ForsendelsesService.retrieveForsendelseStatus();
            inValue.forsendelsesid = forsendelsesid;
            ForsendelseClientSample.ForsendelsesService.retrieveForsendelseStatusResponse retVal = ((ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4)(this)).retrieveForsendelseStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForsendelseClientSample.ForsendelsesService.retrieveForsendelseHistorikkResponse ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4.retrieveForsendelseHistorikk(ForsendelseClientSample.ForsendelsesService.retrieveForsendelseHistorikk request) {
            return base.Channel.retrieveForsendelseHistorikk(request);
        }
        
        public ForsendelseClientSample.ForsendelsesService.hendelsesLogg[] retrieveForsendelseHistorikk(string forsendelsesid) {
            ForsendelseClientSample.ForsendelsesService.retrieveForsendelseHistorikk inValue = new ForsendelseClientSample.ForsendelsesService.retrieveForsendelseHistorikk();
            inValue.forsendelsesid = forsendelsesid;
            ForsendelseClientSample.ForsendelsesService.retrieveForsendelseHistorikkResponse retVal = ((ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4)(this)).retrieveForsendelseHistorikk(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForsendelseClientSample.ForsendelsesService.sendForsendelseResponse ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4.sendForsendelse(ForsendelseClientSample.ForsendelsesService.sendForsendelse request) {
            return base.Channel.sendForsendelse(request);
        }
        
        public string sendForsendelse(ForsendelseClientSample.ForsendelsesService.forsendelse forsendelse) {
            ForsendelseClientSample.ForsendelsesService.sendForsendelse inValue = new ForsendelseClientSample.ForsendelsesService.sendForsendelse();
            inValue.forsendelse = forsendelse;
            ForsendelseClientSample.ForsendelsesService.sendForsendelseResponse retVal = ((ForsendelseClientSample.ForsendelsesService.ForsendelsesServiceV4)(this)).sendForsendelse(inValue);
            return retVal.@return;
        }
    }
}
